# Generated by Django 4.2.5 on 2023-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='mobile',
            new_name='brand',
        ),
    ]
