# Generated by Django 4.2.5 on 2023-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_mobile_mobiles_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='brand',
            field=models.CharField(max_length=120),
        ),
    ]
